#!/bin/sh
convert julia.pgm julia0000.png
for i in julia????.pgm
do
convert $i `basename $i .pgm`.png
done
ffmpeg -framerate 5 -i julia%04d.png -s:v 800x600 -c:v libx264 \
-profile:v high -crf 20 -pix_fmt yuv420p julia.mp4

